### ISSUE TITLE
is render_partial working ?

### ISSUE THREAD

**Issue by euri10** [florimondmanca/asgi-htmx#8]
salut !

I'm playing a little with this repo, after I spent too much time parsing htmx headers so I like the HTMXDetails class a lot now,

However, I started the example but it seems like instead of rendering html, `render_partial` is rendering a string of that html ...

see the screenshot for a better description

is there anything I'm doing incorrectly ?
![20230529_0802_1063x319_1685340172](https://github.com/florimondmanca/asgi-htmx/assets/1104190/07d5bc9b-e40f-4cd0-a62e-9ea089f7983a)

**Comment by euri10** [comment]
well I see how to fix it in the examples but I'm not sure it's the correct way, one could add `safe` to tell jinja2 to escape the created html

https://github.com/florimondmanca/asgi-htmx/blob/f25e1545869bd599b69cfd0fbb049bcf4825a2d3/examples/templates/home.html#L12
could become:
`{{ render_partial('partials/clickme.html', request=request) | safe }} `

there might be a better way ?

**Comment by euri10** [comment]
ok there is: https://github.com/florimondmanca/asgi-htmx/pull/9

**Comment by euri10** [comment]
subsequent question: should render_partial be part of the library ?

**Comment by florimondmanca** [comment]
Hello, and thanks! I think adding markupafe is correct since that’s what Jinja-partials does too: https://github.com/mikeckennedy/jinja_partials/blob/main/jinja_partials/__init__.py (and we can expect our own templates to be « safe »)

> should render_partial be part of the library ?

Not sure? I think people can use jinja-partials. Although I’m curious how most people currently do in practice?

(Initially I copied the code over and adapted it because it was easier to add a Quart utility that way, and I think it’s okay for things to stay this way?)

**Comment by florimondmanca** [comment]
Hmm, so based on https://github.com/PyHAT-stack/awesome-python-htmx  there’s also https://github.com/sponsfreixes/jinja2-fragments

It’s slightly different because it provides a render_block utility instead of render_partial, leveraging the `{% block %}` which seems to be the preferred, more abstracted way now (in fact reflecting non-htmx solutions such as Turbo Frames).

It says it supports “Flask, FastAPI, Quart”, but actually the “FastAPI” module is pure Starlette. So it’s pretty much misbranded… IMO it should be a Starlette module presented as “works with any Starlette-based framework, such as FastAPI”, which incidentally unlocks much more framework compatibility. Maybe I’ll open a discussion there about this.

Anywah, maybe we could rework the example code to use that since it has all the integrations we need for tests. Just a note.
